@baseUrl = http://localhost:3334/api
@authUrl = {{baseUrl}}/auth
@prestamosUrl = {{baseUrl}}/prestamos
@users = rodrigo

@prestamoId = ee2efb5d-5894-4781-b94c-e6343e88b379

### =========================
### AUTH ENDPOINTS
### =========================

### Registrar un nuevo usuario
POST {{authUrl}}/register
Content-Type: application/json

{
  "username": "rodrigo",
  "password": "rodrigo123"
}

### Iniciar sesion
POST {{authUrl}}/login
Content-Type: application/json

{
  "username": "rodrigo",
  "password": "rodrigo123"
}

### Validar token JWT
GET {{authUrl}}/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb2RyaWdvIiwiaWF0IjoxNzc5NTc2Nzk0LCJleHAiOjE3Nzk1ODAzOTR9.IkUrgp1u0vkm9DT5cErYLqKRCVd8iGynmb50Vv_kg2A

### Obtener todos los usuarios y sus tokens
GET {{authUrl}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb2RyaWdvIiwiaWF0IjoxNzc5NTc2Nzk0LCJleHAiOjE3Nzk1ODAzOTR9.IkUrgp1u0vkm9DT5cErYLqKRCVd8iGynmb50Vv_kg2A

### Eliminar un usuario
DELETE {{authUrl}}/users/rodrigo

### =========================
### PRESTAMO-SERVICE ENDPOINTS
### =========================

### Obtener todos los prestamos
GET {{prestamosUrl}} 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb2RyaWdvIiwiaWF0IjoxNzc5NTc2Nzk0LCJleHAiOjE3Nzk1ODAzOTR9.IkUrgp1u0vkm9DT5cErYLqKRCVd8iGynmb50Vv_kg2A

### Obtener prestamos del usuario autenticado
GET {{prestamosUrl}}/usuario
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb2RyaWdvIiwiaWF0IjoxNzc5NTc2Nzk0LCJleHAiOjE3Nzk1ODAzOTR9.IkUrgp1u0vkm9DT5cErYLqKRCVd8iGynmb50Vv_kg2A

### Obtener prestamos por estado
GET {{prestamosUrl}}/estado?estado=ACTIVO
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb2RyaWdvIiwiaWF0IjoxNzc5NTc2Nzk0LCJleHAiOjE3Nzk1ODAzOTR9.IkUrgp1u0vkm9DT5cErYLqKRCVd8iGynmb50Vv_kg2A

### Obtener prestamo por ID
GET {{prestamosUrl}}/{{prestamoId}}
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb2RyaWdvIiwiaWF0IjoxNzc5NTc2Nzk0LCJleHAiOjE3Nzk1ODAzOTR9.IkUrgp1u0vkm9DT5cErYLqKRCVd8iGynmb50Vv_kg2A

### Registrar un nuevo prestamo
POST {{prestamosUrl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb2RyaWdvIiwiaWF0IjoxNzc5NTc2OTA2LCJleHAiOjE3Nzk1ODA1MDZ9.xDl3sO9Rb-DQKJlk1aD5r-iG-CQT2uMi0vWRCeUtciY
{
  "libroId": "ee2efb5d-5894-4781-b94c-e6343e88b379"
}

### Devolver un libro
POST {{prestamosUrl}}/{{prestamoId}}/devolucion
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb2RyaWdvIiwiaWF0IjoxNzc5NTc2Nzk0LCJleHAiOjE3Nzk1ODAzOTR9.IkUrgp1u0vkm9DT5cErYLqKRCVd8iGynmb50Vv_kg2A

### Eliminar un prestamo
DELETE {{prestamosUrl}}/{{prestamoId}}
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb2RyaWdvIiwiaWF0IjoxNzc5NTc2Nzk0LCJleHAiOjE3Nzk1ODAzOTR9.IkUrgp1u0vkm9DT5cErYLqKRCVd8iGynmb50Vv_kg2A

