services:
  postgresPrestamo:
    image: postgres:16-alpine
    container_name: lexicon-prestamo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: prestamo_db
      POSTGRES_USER: prestamo_user
      POSTGRES_PASSWORD: prestamo_pass
    ports:
      - "5434:5432" # <- Puerto exterior único para Préstamos
    volumes:
      - postgres_prestamo_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prestamo_user -d prestamo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_prestamo_data: # <- Volumen exclusivo para guardar los préstamos
  
